# Nom du Worflow
name: 1-Test Connexion Azure

# DÃ©clenchement
on:
  workflow_dispatch


# Variable d'environnement
env:
  LOCATION: westeurope

jobs:
  
  build:
    # Runner
    runs-on: ubuntu-latest
    
    steps:
      - name: Connexion Azure # Nom du 'Step'
        uses: azure/login@v1 # Marketplace 'GitHubAction' https://github.com/marketplace/actions/azure-login
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }} # 'Service Secrets Github' Service Principal Azure

          
           
       # Simple command AZ CLI    
      - run: |
          az group list --query "[?location=='${{ env.LOCATION }}']" --output tsv  
   
    
